name: Remove old artifacts

on:
  schedule:
    - cron: "0 1 */10 * *"

jobs:
  remove-old-artifacts:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Remove old artifacts
        uses: c-hive/gha-remove-artifacts@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          age: "3 day"
          skip-tags: false
